### ISSUE TITLE
Lowercase icon names

### ISSUE THREAD

**Issue by Glazelf** [CrimsonNynja/monster-hunter-DB#48]
Some icons have their names lowercased incorrectly.
Namely (from what I could spot):
Kestodon (male and female, Iceborne)
Gajau (Iceborne)
Teostra (Iceborne)
Scalebat (Iceborne)

My git changes don't seem to recognize capitalization changes in filenames so I would make a very ugly fix probably with multiple commits to get around this, so I think it would be better if you fixed this yourself.

**Comment by CrimsonNynja** [comment]
@Glazelf I would imagine that you are using a mac if you are changing capitalisation and git not recognising the change.

You can force git to recognise this by renaming it using the `git mv` command

for example `git mv ./folder/filename.f ./folder/Filename.f`

This is a quirk of the MacOS where it ignores file capitalisation

**Comment by Glazelf** [comment]
I'm using Windows but I'll try that.
